// app/src/components/ui/Badge.svelte
<script>
  import { cn } from '@/lib/utils.js'
  let { variant = 'default', class: className = '', children } = $props()
  const variants = {
    default: 'bg-primary/15 text-primary border border-primary/30',
    secondary: 'bg-zinc-800 text-zinc-300 border border-zinc-700',
    destructive: 'bg-destructive/15 text-destructive border border-destructive/30',
    success: 'bg-green-500/15 text-green-400 border border-green-500/30',
    outline: 'border border-zinc-700 text-muted-foreground',
  }
</script>

<span class={cn(
  'inline-flex items-center gap-1 rounded-[4px] px-2 py-0.5 text-[11px] font-medium',
  variants[variant] ?? variants.secondary,
  className,
)}>
  {@render children?.()}
</span>

// app/src/components/ui/badge.jsx
import * as React from 'react'
import { Slot } from '@radix-ui/react-slot'
import { cva } from 'class-variance-authority'

import { cn } from '@/lib/utils'

const badgeVariants = cva(
  'inline-flex items-center justify-center rounded-full border px-2 py-0.5 text-xs font-medium w-fit whitespace-nowrap shrink-0 [&>svg]:size-3 gap-1 [&>svg]:pointer-events-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive transition-[color,box-shadow] overflow-hidden',
  {
    variants: {
      variant: {
        default:
          'border-transparent bg-primary text-primary-foreground [a&]:hover:bg-primary/90',
        secondary:
          'border-transparent bg-secondary text-secondary-foreground [a&]:hover:bg-secondary/90',
        destructive:
          'border-transparent bg-destructive text-white [a&]:hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60',
        outline:
          'text-foreground [a&]:hover:bg-accent [a&]:hover:text-accent-foreground',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  },
)

function Badge({ className, variant, asChild = false, ...props }) {
  const Comp = asChild ? Slot : 'span'

  return (
    <Comp
      data-slot="badge"
      className={cn(badgeVariants({ variant }), className)}
      {...props}
    />
  )
}

export { Badge, badgeVariants }
