// app/src/components/ui/Input.svelte
<script>
  import { cn } from '@/lib/utils.js'
  let {
    value = $bindable(''),
    type = 'text',
    placeholder = '',
    disabled = false,
    class: className = '',
    oninput,
    onchange,
    onblur,
    onkeydown,
    ...rest
  } = $props()
</script>

<input
  {type}
  bind:value
  {placeholder}
  {disabled}
  {oninput}
  {onchange}
  {onblur}
  {onkeydown}
  class={cn(
    'h-7 w-full rounded-[6px] border border-zinc-700 bg-zinc-800/60 px-2.5 text-sm text-foreground',
    'placeholder:text-zinc-600 focus:outline-none focus:ring-1 focus:ring-ring',
    'disabled:opacity-50 disabled:cursor-not-allowed',
    className,
  )}
  {...rest}
/>

// app/src/components/ui/input.jsx
import * as React from 'react'

import { cn } from '@/lib/utils'

function Input({ className, type, ...props }) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        'file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
        'focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
        'aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive',
        className,
      )}
      {...props}
    />
  )
}

export { Input }
