// app/src/components/ui/switch.jsx
import * as React from 'react'
import * as SwitchPrimitive from '@radix-ui/react-switch'

import { cn } from '@/lib/utils'

function Switch({ className, ...props }) {
  return (
    <SwitchPrimitive.Root
      data-slot="switch"
      className={cn(
        'peer data-[state=checked]:bg-primary data-[state=unchecked]:bg-input focus-visible:border-ring focus-visible:ring-ring/50 dark:data-[state=unchecked]:bg-input/80 inline-flex h-[1.15rem] w-8 shrink-0 items-center rounded-full border border-transparent shadow-xs transition-all outline-none focus-visible:ring-[3px] cursor-pointer disabled:cursor-not-allowed disabled:opacity-50',
        className,
      )}
      {...props}
    >
      <SwitchPrimitive.Thumb
        data-slot="switch-thumb"
        className={cn(
          'bg-background dark:data-[state=unchecked]:bg-foreground dark:data-[state=checked]:bg-primary-foreground pointer-events-none block size-4 rounded-full ring-0 transition-transform data-[state=checked]:translate-x-[calc(100%-2px)] data-[state=unchecked]:translate-x-0',
        )}
      />
    </SwitchPrimitive.Root>
  )
}

export { Switch }

// app/src/components/ui/Switch.svelte
<script>
  import { cn } from '@/lib/utils.js'
  let {
    checked = $bindable(false),
    id,
    disabled = false,
    onchange,
    class: className = '',
  } = $props()
</script>

<button
  role="switch"
  aria-checked={checked}
  {id}
  {disabled}
  onclick={() => { checked = !checked; onchange?.(checked) }}
  class={cn(
    'relative inline-flex h-5 w-9 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-150',
    'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring',
    'disabled:opacity-50 disabled:cursor-not-allowed',
    checked ? 'bg-primary' : 'bg-zinc-700',
    className,
  )}
>
  <span class={cn(
    'pointer-events-none block h-4 w-4 rounded-full bg-white shadow transition-transform duration-150',
    checked ? 'translate-x-4' : 'translate-x-0',
  )}></span>
</button>
